version: '3.8'

services:
  fraud-detection-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENV=production
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped
    
  fraud-detection-dashboard:
    build: .
    command: streamlit run src/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - fraud-detection-api
    restart: unless-stopped
