version: '3.8'

services:
  fraud-detection-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
      - ENV=production
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  fraud-detection-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    command: streamlit run src/dashboard/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - API_URL=http://fraud-detection-api:8000
    volumes:
      - ./models:/app/models
    depends_on:
      - fraud-detection-api
    restart: unless-stopped
